access_token = 'af0674fe-cd00-4cca-8593-318e38eb61ae'
device_id = '93bcc72d-323e-4549-9aa0-e0465a9a827f'
license_key = 'z50tSP19-19y75Evc-MR526WU7'
private_key = 'WMTPg0nXtBrxrbuQGYHlnT68XPWlRqo23OrilnGBMWc='
