[desktop]
adw-gtk-theme
wallust
realesrgan-ncnn-vulkan-bin
libnotify
upscaler
ffmpeg
gvfs-smb
gvfs-mtp
gvfs
polkit-gnome
exfatprogs
ntfs-3g
polkit
udisks2
nwg-displays
qt5-quickcontrols
qt5-declarative
qt5-svg
qt5-base
tela-circle-icon-theme-nord
ironbar-bin
python-pip
uv
gnome-disk-utility
gparted
xdman-beta-bin
cliphist
xdg-utils
wl-clipboard
cloudflare-warp-bin
python-pywal
waybar
networkmanager
network-manager-applet
proton-vpn-gtk-app
wireguard-tools
openvpn
flatpak
gnome-software
ibus
openbangla-keyboard-bin
fcitx5-qt
fcitx5-gtk
fcitx5-configtool
fcitx5
wlogout
