[desktop]
xdman-beta-bin
cliphist
xdg-utils
wl-clipboard
cloudflare-warp-bin
python-pywal
waybar
networkmanager
network-manager-applet
proton-vpn-gtk-app
wireguard-tools
openvpn
flatpak
gnome-software
ibus
openbangla-keyboard-bin
fcitx5-qt
fcitx5-gtk
fcitx5-configtool
fcitx5
wlogout
