# General type packages

[dev]
ngrok

[fonts]
ttf-fantasque-sans-mono
ttf-fantasque-nerd
noto-fonts-extra
noto-fonts-emoji
noto-fonts-cjk
noto-fonts
inter-font
ttf-liberation
ttf-dejavu

[ml]
lmstudio
