# ~/.config/wallust/wallust.toml

# =========================================
# BACKEND SETTINGS
# Options: full, resized, wal, thumb, fastresize, kmeans
# Full       - Read and return the whole image pixels (more precision, slower)
# Resized    - Resizes the image before parsing, mantaining it's aspect ratio
# Wal        - Uses image magick convert to generate the colors, like pywal
# Thumb      - Faster algo hardcoded to 512x512 (no ratio respected)
# FastResize - A much faster resize algo that uses SIMD. For some reason it fails on some images where resized doesn't, for this reason it doesn't replace but rather it's a new option.
# Kmeans     - Kmeans is an algo that divides and picks pixels all around the image, giving a more diverse look.

# =========================================
backend = "wal"
color_space = "lch"
palette = "dark16"
check_contrast = true

# =========================================
# TEMPLATES (v3 Syntax)
# =========================================
[templates]

# template_name = { template = "source", target = "destination" }

hyprland = { template = "hyprland-colors.conf", target = "~/.config/hypr/colors.conf" }

waybar = { template = "waybar-colors.template", target = "~/.config/waybar/colors.css" }

dunst = { template = "dunstrc", target = "~/.config/dunst/dunstrc" }

rofi = { template = "rofi-colors.rasi", target = "~/.config/rofi/colors/wallust.rasi" }

kitty = { template = "kitty-colors.conf", target = "~/.config/kitty/colors.conf" }

# GTK 4
gtk4 = { template = "gtk.template", target = "~/.config/gtk-4.0/colors.css" }

# GTK 3
gtk3 = { template = "gtk.template", target = "~/.config/gtk-3.0/colors.css" }

# wlogout
wlogout = { template = "wlogout.template", target = "~/.config/wlogout/style.css" }

# Qt (qt5ct/qt6ct)
qt = { template = "qt-colors.conf", target = "~/.config/qt5ct/colors/wally.conf" }
qt6 = { template = "qt-colors.conf", target = "~/.config/qt6ct/colors/wally.conf" }

# Vencord / Discord Theme
# If you use Vesktop, change path to: ~/.config/vesktop/themes/wally.theme.css
discord = { template = "discord.template", target = "~/.config/Vencord/themes/midnight-wallust.theme.css" }

# Tmux
tmux = { template = "tmux-colors.conf", target = "~/.tmux-colors.conf" }

# Sddm
sddm = { template = "sddm.conf" , target = "~/dotfiles/sddm/themes/silent/configs/default.conf"}
