# Arch Linux Package List
# This file tracks packages installed via pacman, yay, and paru
#
# Format: [category:package_manager]
#   - [cli:pacman] = CLI packages installed via pacman
#   - [desktop:pacman] = Desktop packages installed via pacman
#   - [gaming:pacman] = Gaming packages installed via pacman
#   - Packages are auto-categorized based on GAMING_PACKAGES and CLI_PACKAGES maps
#   - Unknown packages default to "desktop" category

# CLI packages
[cli:pacman]
go
btop
less
gum
neovim
bat
git
tree
docker-compose
docker
tmux
zsh
php
composer
stow
curl
wget
imagemagick
php-imagick


# Desktop packages
[desktop:pacman]
adw-gtk-theme
libnotify
gnome-software
ffmpeg
gvfs-smb
gvfs-mtp
gvfs
polkit-gnome
exfatprogs
ntfs-3g
polkit
udisks2
nwg-displays
qt5-quickcontrols
qt5-declarative
qt5-svg
qt5-base
tela-circle-icon-theme-nord
python-pip
uv
gnome-disk-utility
gparted
cliphist
xdg-utils
wl-clipboard
python-pywal
waybar
network-manager-applet
networkmanager
proton-vpn-gtk-app
wireguard-tools
openvpn
flatpak
ibus
blueman
i2c-tools
kitty
rofi
swww
hyprshot
qt5ct
chromium
brightnessctl

[cli:yay]

[desktop:yay]
vencord-installer-bin
wallust
realesrgan-ncnn-vulkan-bin
upscaler
ironbar-bin
xdman-beta-bin
cloudflare-warp-bin
wlogout
google-chrome
greenclip
openrgb-bin

[cli:paru]

[desktop:paru]

# Gaming packages
[gaming:pacman]
obs-studio
vulkan-icd-loader
discord
mangohud
lib32-vulkan-icd-loader
lutris
steam
winetricks
wine-mono
wine-staging

[gaming:yay]
heroic-games-launcher-bin
protonup-qt

[gaming:paru]

[dev:yay]
ngrok

[fonts:pacman]
ttf-iosevka-nerd
ttf-fantasque-sans-mono
ttf-fantasque-nerd
noto-fonts-extra
noto-fonts-emoji
noto-fonts-cjk
noto-fonts
inter-font
ttf-liberation
ttf-dejavu

[ml:yay]
lmstudio
